source 'https://rubygems.org'

gem 'sqlite3', '~> 2.1'
gem 'activerecord', '~> 8.1'
gem 'standalone_migrations', '~> 8.1'
gem 'nokogiri', '~> 1.16'
gem 'faraday', '~> 2.9'
gem 'faraday-follow_redirects', '~> 0.3'

group :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
  gem 'database_cleaner-active_record'
  gem 'factory_bot', '~> 6.4'
end
